FROM balenalib/%%BALENA_ARCH%%-alpine-python:3.7-run
LABEL maintainer="Evan Bovie <evan@bovie.me>"
WORKDIR /app

ARG HC_BUILD_VERSION

RUN install_packages bash git openssh && \
    pip install --no-cache-dir hass-configurator==${HC_BUILD_VERSION} gitpython pyotp

COPY ./run.sh /app/
RUN chmod a+x ./run.sh

EXPOSE 3218
VOLUME /config
ENTRYPOINT ["/app/run.sh"]

